chore: refactor image-bin uploader
blocklet/image-bin pull request #72
Opened 2023-09-01 11:13 UTC by FireTable

### 关联 Issue

https://github.com/blocklet/image-bin/issues/61

https://github.com/blocklet/image-bin/issues/20

https://github.com/blocklet/image-bin/issues/67

### 主要改动

1. 编写 @blocklet/uploader 组件，使用 uppy 相关依赖，并且兼容 blocklet server 体系
   - 支持断点续连
   - 支持 unsplash、远程图片，且可以本地编辑
   - 支持一次性上传多张不同来源的图片
   - 支持剪切板、拖拽文件、拖拽文件夹导入
   - 支持后台上传传图
2. 使用 @blocklet/uploader  组件进行 image-bin 重构（还没重构界面）
3. 支持 blcoklet.yml 录入 unsplash_key、unsplash_secret
4. 修复文件限制计算的 bug，1MB 等于 1024 * 1024 b
5. 移除后端 shark 压缩图片的逻辑，后期使用 image service，防止二次压缩

### 界面截图

// chrome
// 打包后 根目录正常
![image](https://github.com/blocklet/image-bin/assets/24667209/41375485-332a-4f9d-8768-eb7e6fc9b338)

// 打包后子组件正常
![image](https://github.com/blocklet/image-bin/assets/24667209/4c906c8b-207f-4c24-b7e6-ced8ca3f3a0a)

//safari
<img width="1438" alt="image" src="https://github.com/blocklet/image-bin/assets/24667209/7526723d-9a28-414b-8030-d99219fe4f10">

// mobile
![image](https://github.com/blocklet/image-bin/assets/24667209/79617a24-2b09-4788-b8f2-80bfa02d90c8)

### 测试计划

- [x] 本地回归测试
   - [x] 本地图片上传正常
   - [x] 远程图片上传正常
   - [x] upsplash 上传正常  
   - [x] 挂载为子组件再测试
   

### 检查清单

- [x] 本次变更的兼容性测试覆盖了 Safari
- [x] 本次变更的兼容性测试覆盖了 Chrome
- [x] 本次变更的兼容性测试覆盖了移动端【手机浏览器、钱包内置浏览器】
- [x] 本次变更增加了依赖

2023-09-01 23:23 UTC, wangshijun requested changes

2023-09-01 23:23 UTC, wangshijun commented on blocklets/image-bin/api/libs/env.js
> +  providerOptions: {
建议这部分做到 preferences 里面去，如果有配置，前端展示 unsplash，如果没配置，前端不展示 unsplash

2023-09-01 23:23 UTC, wangshijun commented on blocklets/image-bin/blocklet.yml
> +version: 0.9.22
这个应该 bump 到 0.10.0

2023-09-01 23:23 UTC, wangshijun commented on blocklets/image-bin/src/app.jsx
> +// const ImageList = lazy(() => import('./pages/images'));
删掉

2023-09-01 23:23 UTC, wangshijun commented on packages/uploader/README.md
> +# Blocklet Embed
这个 readme 需要更新，包含正确的用法，相当于写个简单的使用文档

2023-09-01 23:23 UTC, wangshijun commented on packages/uploader/src/middlewares/local-storage.ts
> +      const ext = req.headers['x-uploader-file-ext'];
能用文件内容 hash 命名么？

2023-09-01 23:23 UTC, wangshijun commented on packages/uploader/src/middlewares/local-storage.ts
> +  // default root path
不需要的可以删

2023-09-01 23:23 UTC, wangshijun commented on packages/uploader/src/middlewares/local-storage.ts
> +  if (method === 'post' && !req.baseUrl.startsWith(headers['x-path-prefix'])) {
看下 `@blocklet/sdk/lib/component#getUrl`

2023-09-01 23:23 UTC, wangshijun commented on packages/uploader/src/react/plugins/prepare-upload.jsx
> +        downloadingFiles: 'Downloading remote files...',
文案最好做下 i18n，我们的基础组件应该标配

2023-09-02 06:05 UTC, FireTable commented on blocklets/image-bin/api/libs/env.js
> +  providerOptions: {
目前我放在了环境变量里面，如果环境变量没配置 key、secrect，也不会显示前端的 unsplash（根据 key 判断的）

我感觉因为有 secret，所以不好放在 preferences 里面? 容易泄露?

2023-09-02 06:07 UTC, FireTable commented on packages/uploader/src/middlewares/local-storage.ts
> +      const ext = req.headers['x-uploader-file-ext'];
这个 x-uploader-filename 如果传过来了，就是用了 hash 来做命名的，前端做了计算
几乎不可能不穿过来，因为组件里面每次请求都会附带

只是排除一些情况，比如 headers 黑名单被拦截，所以有个 random name

2023-09-02 06:11 UTC, FireTable commented on packages/uploader/src/middlewares/local-storage.ts
> +  // default root path
done

2023-09-02 06:11 UTC, FireTable commented on blocklets/image-bin/src/app.jsx
> +// const ImageList = lazy(() => import('./pages/images'));
done

2023-09-02 06:11 UTC, FireTable commented on blocklets/image-bin/blocklet.yml
> +version: 0.9.22
done

2023-09-02 06:11 UTC, FireTable commented on packages/uploader/src/react/plugins/prepare-upload.jsx
> +        downloadingFiles: 'Downloading remote files...',
这个后续再一起做，包括 image-bin 的 i18n 和组件的

2023-09-02 06:12 UTC, FireTable commented on packages/uploader/src/react/plugins/prepare-upload.jsx
> +        downloadingFiles: 'Downloading remote files...',
https://github.com/blocklet/image-bin/issues/new?assignees=&labels=discuss,+feature&projects=&template=feature-request.md&title=%5B+Feature+%5D

2023-09-02 06:40 UTC, FireTable commented on packages/uploader/src/middlewares/local-storage.ts
> +  if (method === 'post' && !req.baseUrl.startsWith(headers['x-path-prefix'])) {
做了一版兼容

这个一开始没用 getUrl，是因为考虑到像 server 也会使用这个组件，那它是没有 BLOCKLET_COMPONENT_DID
目前改造成如果有 BLOCKLET_COMPONENT_DID 优先用

2023-09-02 06:41 UTC, FireTable commented on packages/uploader/README.md
> +# Blocklet Embed
done

2023-09-03 08:27 UTC, wangshijun approved these changes

2023-09-03 23:50 UTC, wangshijun commented on blocklets/image-bin/api/libs/env.js
> +  providerOptions: {
https://github.com/ArcBlock/blocklet-server/pull/7568

2023-09-04 03:31 UTC, merged